### ISSUE TITLE
Date that already includes daylight saving is compared incorrectly

### ISSUE THREAD

**Issue by vivaladan** [wildlyinaccurate/angular-relative-date#12]
The date string I'm using the filter upon is already correct with respect to daylight saving changes. This is because the API that it comes from is returning local time, in this case GMT+1.

Using this string as a parameter to the js date obj inside the filter, applies +1 again. This means that the calculated relative time is out by an hour having had DST corrected twice.

---
As I can't change the web-server to return UTC without DST, I've used moment.js and it's relative time function inside my own angular filter.

**Comment by wildlyinaccurate** [comment]
Thanks for raising this. Off the top of my head, I think there are a couple of ways you can fix this:

 1. Provide a date object with timezone set to DST as the `now` value 
 2. Convert all of the dates you run through the filter to UTC

I'll try and figure a way to do this automatically from the filter. I guess the problem is that the default value for `now` will have the user's timezone (since it's constructed just as `new Date()`). Perhaps the timezone for `now` can be inferred from the date object which is passed from the filter?
